---
- hosts: 'all'
  sudo: yes
  sudo_user: root

  pre_tasks:

    - name: Install performance monitoring tools first
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - htop
        - iotop
        - iftop
        - nethogs
        - mtr-tiny

    - name: Install basic packages
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - etckeeper
        - git
        - curl
        - ca-certificates
        - locales
        - locales-all
        - resolvconf
        - firmware-linux
        - apt-transport-https

    - include: sid.yml
      when: ansible_lsb.codename == 'sid'

  roles:

    - role: aptsource
      aptsource_suite: stretch
      when: ansible_lsb.codename == 'jessie'

    - role: aptsource
      aptsource_suite: sid
      when: ansible_lsb.codename == 'stretch'

  post_tasks:

    - include: dist-upgrade.yml
      when: ansible_lsb.codename != 'sid'
